### PR TITLE
feat(omni_txn): Introduce a timeout parameter to retry

### PR DESCRIPTION
**Pull request by AJ0070**
fixes: #669 

### Implemented Solution:
A `timeout_ms` parameter has been added to the `omni_txn.retry` function. This allows developers to specify a maximum duration for the entire retry process. If the elapsed time exceeds this timeout, the function will stop retrying and raise an error.

This change is backward-compatible. Existing calls to the function will continue to work as before, with the timeout defaulting to disabled.

### Changes:
- `extensions/omni_txn/retry.c`: Modified to include the timeout logic.
- `extensions/omni_txn/migrate/7_add_retry_timeout.sql`: New migration file to update the SQL function signature.
- `extensions/omni_txn/tests/retry.yml`: Added a new test case to verify the timeout functionality.

Happy to iterate to get the best solution possible.

### CODE REVIEW

**Comment by yrashk** [comment]
Thank you! master CI failure is being fixed in #883 

However, I noticed that the non-master tests fail:

```
        error: "omni_txn.retry(text, integer, boolean, boolean, record, boolean) is not a function"    
```

Have you run the tests locally before submitting the PR?
