### ISSUE TITLE
Problem: CI is currently failing since unable to build Omnigres docker image

### ISSUE THREAD

**Issue by viggy28** [omnigres/omnigres#419]
Likely a regression introduced by https://github.com/omnigres/omnigres/pull/390 is causing a failure on the CI step. 

```
#20 877.4 /usr/bin/ld: be-secure-openssl.c:(.text+0x1c0a): undefined reference to `ERR_set_error'
#20 877.4 /usr/bin/ld: be-secure-openssl.c:(.text+0x1c2b): undefined reference to `ERR_new'
#20 877.4 /usr/bin/ld: be-secure-openssl.c:(.text+0x1c43): undefined reference to `ERR_set_debug'
#20 877.4 /usr/bin/ld: be-secure-openssl.c:(.text+0x1c5c): undefined reference to `ERR_set_error'
#20 877.5 collect2: error: ld returned 1 exit status
#20 877.5 make[2]: *** [Makefile:68: postgres] Error 1
#20 877.5 make[2]: Leaving directory '/omni/.pg/Linux-Release/16.1/postgresql-16.1/src/backend'
#20 877.5 make[1]: *** [Makefile:42: install-backend-recurse] Error 2
#20 877.5 make[1]: Leaving directory '/omni/.pg/Linux-Release/16.1/postgresql-16.1/src'
#20 877.5 make: *** [GNUmakefile:11: install-src-recurse] Error 2
#20 877.6 CMake Error at cmake/FindPostgreSQL.cmake:177 (message):
#20 877.6   Can't build Postgres, aborting.
#20 877.6 Call Stack (most recent call first):
#20 877.6   CMakeLists.txt:6 (find_package)
#20 877.6 
#20 877.6 
#20 877.6 -- Configuring incomplete, errors occurred!
```

**Comment by yrashk** [comment]
Solved in #421
